version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - auth
      - event

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - '3002:3002'
    depends_on:
      - mongo

  event:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mongo

volumes:
  mongo-data:
