version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - auth
      - event
    networks:
      - app-network

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - '3002:3002'
    depends_on:
      - mongo
    networks:
      - app-network

  event:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
